sudo -S pacman -S --noconfirm a52dec
sudo -S pacman -S --noconfirm aalib
sudo -S pacman -S --noconfirm abseil-cpp
sudo -S pacman -S --noconfirm accounts-qml-module
sudo -S pacman -S --noconfirm accountsservice
sudo -S pacman -S --noconfirm acl
sudo -S pacman -S --noconfirm adobe-source-han-sans-cn-fonts
sudo -S pacman -S --noconfirm adobe-source-han-sans-jp-fonts
sudo -S pacman -S --noconfirm adobe-source-han-sans-kr-fonts
sudo -S pacman -S --noconfirm adwaita-cursors
sudo -S pacman -S --noconfirm adwaita-fonts
sudo -S pacman -S --noconfirm adwaita-icon-theme
sudo -S pacman -S --noconfirm adwaita-icon-theme-legacy
sudo -S pacman -S --noconfirm aha
sudo -S pacman -S --noconfirm alacritty
sudo -S pacman -S --noconfirm alsa-card-profiles
sudo -S pacman -S --noconfirm alsa-firmware
sudo -S pacman -S --noconfirm alsa-lib
sudo -S pacman -S --noconfirm alsa-plugins
sudo -S pacman -S --noconfirm alsa-topology-conf
sudo -S pacman -S --noconfirm alsa-ucm-conf
sudo -S pacman -S --noconfirm alsa-utils
sudo -S pacman -S --noconfirm amd-ucode
sudo -S pacman -S --noconfirm ananicy-cpp
sudo -S pacman -S --noconfirm aom
sudo -S pacman -S --noconfirm appstream
sudo -S pacman -S --noconfirm appstream-qt
sudo -S pacman -S --noconfirm archlinux-keyring
sudo -S pacman -S --noconfirm aribb24
sudo -S pacman -S --noconfirm aribb25
sudo -S pacman -S --noconfirm ark
sudo -S pacman -S --noconfirm at-spi2-core
sudo -S pacman -S --noconfirm atkmm
sudo -S pacman -S --noconfirm attica
sudo -S pacman -S --noconfirm attr
sudo -S pacman -S --noconfirm audit
sudo -S pacman -S --noconfirm aurorae
sudo -S pacman -S --noconfirm autoconf
sudo -S pacman -S --noconfirm automake
sudo -S pacman -S --noconfirm avahi
sudo -S pacman -S --noconfirm awesome-terminal-fonts
sudo -S pacman -S --noconfirm baloo
sudo -S pacman -S --noconfirm baloo-widgets
sudo -S pacman -S --noconfirm base
sudo -S pacman -S --noconfirm base-devel
sudo -S pacman -S --noconfirm bash
sudo -S pacman -S --noconfirm bash-completion
sudo -S pacman -S --noconfirm bat
sudo -S pacman -S --noconfirm bind
sudo -S pacman -S --noconfirm binutils
sudo -S pacman -S --noconfirm bison
sudo -S pacman -S --noconfirm blas
sudo -S pacman -S --noconfirm bluedevil
sudo -S pacman -S --noconfirm bluez
sudo -S pacman -S --noconfirm bluez-hid2hci
sudo -S pacman -S --noconfirm bluez-libs
sudo -S pacman -S --noconfirm bluez-qt
sudo -S pacman -S --noconfirm bluez-utils
sudo -S pacman -S --noconfirm bolt
sudo -S pacman -S --noconfirm bpf
sudo -S pacman -S --noconfirm breeze
sudo -S pacman -S --noconfirm breeze-gtk
sudo -S pacman -S --noconfirm breeze-icons
sudo -S pacman -S --noconfirm brotli
sudo -S pacman -S --noconfirm btop
sudo -S pacman -S --noconfirm btrfs-progs
sudo -S pacman -S --noconfirm bubblewrap
sudo -S pacman -S --noconfirm bzip2
sudo -S pacman -S --noconfirm ca-certificates
sudo -S pacman -S --noconfirm ca-certificates-mozilla
sudo -S pacman -S --noconfirm ca-certificates-utils
sudo -S pacman -S --noconfirm cachyos-alacritty-config
sudo -S pacman -S --noconfirm cachyos-ananicy-rules
sudo -S pacman -S --noconfirm cachyos-emerald-kde-theme-git
sudo -S pacman -S --noconfirm cachyos-fish-config
sudo -S pacman -S --noconfirm cachyos-grub-theme
sudo -S pacman -S --noconfirm cachyos-hello
sudo -S pacman -S --noconfirm cachyos-hooks
sudo -S pacman -S --noconfirm cachyos-iridescent-kde
sudo -S pacman -S --noconfirm cachyos-kde-settings
sudo -S pacman -S --noconfirm cachyos-kernel-manager
sudo -S pacman -S --noconfirm cachyos-keyring
sudo -S pacman -S --noconfirm cachyos-micro-settings
sudo -S pacman -S --noconfirm cachyos-mirrorlist
sudo -S pacman -S --noconfirm cachyos-nord-kde-theme-git
sudo -S pacman -S --noconfirm cachyos-packageinstaller
sudo -S pacman -S --noconfirm cachyos-plymouth-bootanimation
sudo -S pacman -S --noconfirm cachyos-rate-mirrors
sudo -S pacman -S --noconfirm cachyos-settings
sudo -S pacman -S --noconfirm cachyos-themes-sddm
sudo -S pacman -S --noconfirm cachyos-v3-mirrorlist
sudo -S pacman -S --noconfirm cachyos-v4-mirrorlist
sudo -S pacman -S --noconfirm cachyos-wallpapers
sudo -S pacman -S --noconfirm cachyos-zsh-config
sudo -S pacman -S --noconfirm cairo
sudo -S pacman -S --noconfirm cairomm
sudo -S pacman -S --noconfirm cairomm-1.16
sudo -S pacman -S --noconfirm cantarell-fonts
sudo -S pacman -S --noconfirm capitaine-cursors
sudo -S pacman -S --noconfirm cblas
sudo -S pacman -S --noconfirm cdparanoia
sudo -S pacman -S --noconfirm cfitsio
sudo -S pacman -S --noconfirm char-white
sudo -S pacman -S --noconfirm chromaprint
sudo -S pacman -S --noconfirm chwd
sudo -S pacman -S --noconfirm cifs-utils
sudo -S pacman -S --noconfirm clang
sudo -S pacman -S --noconfirm clinfo
sudo -S pacman -S --noconfirm compiler-rt
sudo -S pacman -S --noconfirm confuse
sudo -S pacman -S --noconfirm convertlit
sudo -S pacman -S --noconfirm coreutils
sudo -S pacman -S --noconfirm cpupower
sudo -S pacman -S --noconfirm cryptsetup
sudo -S pacman -S --noconfirm curl
sudo -S pacman -S --noconfirm dav1d
sudo -S pacman -S --noconfirm db5.3
sudo -S pacman -S --noconfirm dbus
sudo -S pacman -S --noconfirm dbus-broker
sudo -S pacman -S --noconfirm dbus-broker-units
sudo -S pacman -S --noconfirm dbus-units
sudo -S pacman -S --noconfirm dconf
sudo -S pacman -S --noconfirm ddcutil
sudo -S pacman -S --noconfirm debugedit
sudo -S pacman -S --noconfirm default-cursors
sudo -S pacman -S --noconfirm desktop-file-utils
sudo -S pacman -S --noconfirm device-mapper
sudo -S pacman -S --noconfirm dhclient
sudo -S pacman -S --noconfirm diffutils
sudo -S pacman -S --noconfirm ding-libs
sudo -S pacman -S --noconfirm dmidecode
sudo -S pacman -S --noconfirm dmraid
sudo -S pacman -S --noconfirm dnsmasq
sudo -S pacman -S --noconfirm dnssec-anchors
sudo -S pacman -S --noconfirm dolphin
sudo -S pacman -S --noconfirm dosfstools
sudo -S pacman -S --noconfirm double-conversion
sudo -S pacman -S --noconfirm duf
sudo -S pacman -S --noconfirm duktape
sudo -S pacman -S --noconfirm e2fsprogs
sudo -S pacman -S --noconfirm ebook-tools
sudo -S pacman -S --noconfirm editorconfig-core-c
sudo -S pacman -S --noconfirm efibootmgr
sudo -S pacman -S --noconfirm efitools
sudo -S pacman -S --noconfirm efivar
sudo -S pacman -S --noconfirm egl-wayland
sudo -S pacman -S --noconfirm eglexternalplatform
sudo -S pacman -S --noconfirm ell
sudo -S pacman -S --noconfirm ethtool
sudo -S pacman -S --noconfirm exfatprogs
sudo -S pacman -S --noconfirm exiv2
sudo -S pacman -S --noconfirm expac
sudo -S pacman -S --noconfirm expat
sudo -S pacman -S --noconfirm eza
sudo -S pacman -S --noconfirm f2fs-tools
sudo -S pacman -S --noconfirm faac
sudo -S pacman -S --noconfirm faad2
sudo -S pacman -S --noconfirm fakeroot
sudo -S pacman -S --noconfirm fastfetch
sudo -S pacman -S --noconfirm fd
sudo -S pacman -S --noconfirm ffmpeg
sudo -S pacman -S --noconfirm ffmpeg4.4
sudo -S pacman -S --noconfirm ffmpegthumbnailer
sudo -S pacman -S --noconfirm ffmpegthumbs
sudo -S pacman -S --noconfirm fftw
sudo -S pacman -S --noconfirm file
sudo -S pacman -S --noconfirm filelight
sudo -S pacman -S --noconfirm filesystem
sudo -S pacman -S --noconfirm findutils
sudo -S pacman -S --noconfirm firefox
sudo -S pacman -S --noconfirm fish
sudo -S pacman -S --noconfirm fish-autopair
sudo -S pacman -S --noconfirm fish-pure-prompt
sudo -S pacman -S --noconfirm fisher
sudo -S pacman -S --noconfirm flac
sudo -S pacman -S --noconfirm flashrom
sudo -S pacman -S --noconfirm flex
sudo -S pacman -S --noconfirm fluidsynth
sudo -S pacman -S --noconfirm fmt
sudo -S pacman -S --noconfirm fontconfig
sudo -S pacman -S --noconfirm frameworkintegration
sudo -S pacman -S --noconfirm freeglut
sudo -S pacman -S --noconfirm freetype2
sudo -S pacman -S --noconfirm fribidi
sudo -S pacman -S --noconfirm fsarchiver
sudo -S pacman -S --noconfirm ftgl
sudo -S pacman -S --noconfirm fuse-common
sudo -S pacman -S --noconfirm fuse3
sudo -S pacman -S --noconfirm fwupd
sudo -S pacman -S --noconfirm fwupd-efi
sudo -S pacman -S --noconfirm fzf
sudo -S pacman -S --noconfirm gawk
sudo -S pacman -S --noconfirm gc
sudo -S pacman -S --noconfirm gcc
sudo -S pacman -S --noconfirm gcc-libs
sudo -S pacman -S --noconfirm gdbm
sudo -S pacman -S --noconfirm gdk-pixbuf2
sudo -S pacman -S --noconfirm gettext
sudo -S pacman -S --noconfirm ghostscript
sudo -S pacman -S --noconfirm giflib
sudo -S pacman -S --noconfirm git
sudo -S pacman -S --noconfirm glances
sudo -S pacman -S --noconfirm glew
sudo -S pacman -S --noconfirm glib-networking
sudo -S pacman -S --noconfirm glib2
sudo -S pacman -S --noconfirm glibc
sudo -S pacman -S --noconfirm glibmm
sudo -S pacman -S --noconfirm glibmm-2.68
sudo -S pacman -S --noconfirm glm
sudo -S pacman -S --noconfirm glslang
sudo -S pacman -S --noconfirm glu
sudo -S pacman -S --noconfirm glycin
sudo -S pacman -S --noconfirm gmp
sudo -S pacman -S --noconfirm gnulib-l10n
sudo -S pacman -S --noconfirm gnupg
sudo -S pacman -S --noconfirm gnutls
sudo -S pacman -S --noconfirm gobject-introspection-runtime
sudo -S pacman -S --noconfirm gperftools
sudo -S pacman -S --noconfirm gpgme
sudo -S pacman -S --noconfirm gpgmepp
sudo -S pacman -S --noconfirm gpm
sudo -S pacman -S --noconfirm graphene
sudo -S pacman -S --noconfirm graphite
sudo -S pacman -S --noconfirm grep
sudo -S pacman -S --noconfirm groff
sudo -S pacman -S --noconfirm grub
sudo -S pacman -S --noconfirm grub-hook
sudo -S pacman -S --noconfirm gsettings-desktop-schemas
sudo -S pacman -S --noconfirm gsettings-system-schemas
sudo -S pacman -S --noconfirm gsm
sudo -S pacman -S --noconfirm gssdp
sudo -S pacman -S --noconfirm gssproxy
sudo -S pacman -S --noconfirm gst-libav
sudo -S pacman -S --noconfirm gst-plugin-pipewire
sudo -S pacman -S --noconfirm gst-plugins-bad
sudo -S pacman -S --noconfirm gst-plugins-bad-libs
sudo -S pacman -S --noconfirm gst-plugins-base
sudo -S pacman -S --noconfirm gst-plugins-base-libs
sudo -S pacman -S --noconfirm gst-plugins-ugly
sudo -S pacman -S --noconfirm gstreamer
sudo -S pacman -S --noconfirm gtest
sudo -S pacman -S --noconfirm gtk-update-icon-cache
sudo -S pacman -S --noconfirm gtk3
sudo -S pacman -S --noconfirm gtk4
sudo -S pacman -S --noconfirm gtkmm-4.0
sudo -S pacman -S --noconfirm gtkmm3
sudo -S pacman -S --noconfirm gtksourceview4
sudo -S pacman -S --noconfirm guile
sudo -S pacman -S --noconfirm gupnp
sudo -S pacman -S --noconfirm gupnp-igd
sudo -S pacman -S --noconfirm gwenview
sudo -S pacman -S --noconfirm gzip
sudo -S pacman -S --noconfirm harfbuzz
sudo -S pacman -S --noconfirm haruna
sudo -S pacman -S --noconfirm haveged
sudo -S pacman -S --noconfirm hdparm
sudo -S pacman -S --noconfirm hicolor-icon-theme
sudo -S pacman -S --noconfirm hidapi
sudo -S pacman -S --noconfirm highway
sudo -S pacman -S --noconfirm hunspell
sudo -S pacman -S --noconfirm hwdata
sudo -S pacman -S --noconfirm hwdetect
sudo -S pacman -S --noconfirm hwinfo
sudo -S pacman -S --noconfirm hwloc
sudo -S pacman -S --noconfirm i2c-tools
sudo -S pacman -S --noconfirm iana-etc
sudo -S pacman -S --noconfirm icu
sudo -S pacman -S --noconfirm ijs
sudo -S pacman -S --noconfirm imagemagick
sudo -S pacman -S --noconfirm imath
sudo -S pacman -S --noconfirm imlib2
sudo -S pacman -S --noconfirm inetutils
sudo -S pacman -S --noconfirm inxi
sudo -S pacman -S --noconfirm iproute2
sudo -S pacman -S --noconfirm iptables-nft
sudo -S pacman -S --noconfirm iputils
sudo -S pacman -S --noconfirm iso-codes
sudo -S pacman -S --noconfirm iw
sudo -S pacman -S --noconfirm iwd
sudo -S pacman -S --noconfirm jack2
sudo -S pacman -S --noconfirm jansson
sudo -S pacman -S --noconfirm jasper
sudo -S pacman -S --noconfirm jbig2dec
sudo -S pacman -S --noconfirm jbigkit
sudo -S pacman -S --noconfirm jemalloc
sudo -S pacman -S --noconfirm jfsutils
sudo -S pacman -S --noconfirm jq
sudo -S pacman -S --noconfirm json-c
sudo -S pacman -S --noconfirm json-glib
sudo -S pacman -S --noconfirm jsoncpp
sudo -S pacman -S --noconfirm kaccounts-integration
sudo -S pacman -S --noconfirm kactivitymanagerd
sudo -S pacman -S --noconfirm karchive
sudo -S pacman -S --noconfirm kate
sudo -S pacman -S --noconfirm kauth
sudo -S pacman -S --noconfirm kbd
sudo -S pacman -S --noconfirm kbookmarks
sudo -S pacman -S --noconfirm kcalc
sudo -S pacman -S --noconfirm kcmutils
sudo -S pacman -S --noconfirm kcodecs
sudo -S pacman -S --noconfirm kcolorpicker
sudo -S pacman -S --noconfirm kcolorscheme
sudo -S pacman -S --noconfirm kcompletion
sudo -S pacman -S --noconfirm kconfig
sudo -S pacman -S --noconfirm kconfigwidgets
sudo -S pacman -S --noconfirm kcontacts
sudo -S pacman -S --noconfirm kcoreaddons
sudo -S pacman -S --noconfirm kcrash
sudo -S pacman -S --noconfirm kdbusaddons
sudo -S pacman -S --noconfirm kde-cli-tools
sudo -S pacman -S --noconfirm kde-gtk-config
sudo -S pacman -S --noconfirm kdeclarative
sudo -S pacman -S --noconfirm kdeconnect
sudo -S pacman -S --noconfirm kdecoration
sudo -S pacman -S --noconfirm kded
sudo -S pacman -S --noconfirm kdegraphics-mobipocket
sudo -S pacman -S --noconfirm kdegraphics-thumbnailers
sudo -S pacman -S --noconfirm kdeplasma-addons
sudo -S pacman -S --noconfirm kdesu
sudo -S pacman -S --noconfirm kdialog
sudo -S pacman -S --noconfirm kdnssd
sudo -S pacman -S --noconfirm kdsingleapplication
sudo -S pacman -S --noconfirm kdsoap-qt6
sudo -S pacman -S --noconfirm kdsoap-ws-discovery-client
sudo -S pacman -S --noconfirm keyutils
sudo -S pacman -S --noconfirm kfilemetadata
sudo -S pacman -S --noconfirm kglobalaccel
sudo -S pacman -S --noconfirm kglobalacceld
sudo -S pacman -S --noconfirm kguiaddons
sudo -S pacman -S --noconfirm kholidays
sudo -S pacman -S --noconfirm ki18n
sudo -S pacman -S --noconfirm kiconthemes
sudo -S pacman -S --noconfirm kidletime
sudo -S pacman -S --noconfirm kimageannotator
sudo -S pacman -S --noconfirm kinfocenter
sudo -S pacman -S --noconfirm kio
sudo -S pacman -S --noconfirm kio-admin
sudo -S pacman -S --noconfirm kio-extras
sudo -S pacman -S --noconfirm kio-fuse
sudo -S pacman -S --noconfirm kirigami
sudo -S pacman -S --noconfirm kirigami-addons
sudo -S pacman -S --noconfirm kitemmodels
sudo -S pacman -S --noconfirm kitemviews
sudo -S pacman -S --noconfirm kjobwidgets
sudo -S pacman -S --noconfirm kmenuedit
sudo -S pacman -S --noconfirm kmod
sudo -S pacman -S --noconfirm knewstuff
sudo -S pacman -S --noconfirm knotifications
sudo -S pacman -S --noconfirm knotifyconfig
sudo -S pacman -S --noconfirm konsole
sudo -S pacman -S --noconfirm kpackage
sudo -S pacman -S --noconfirm kparts
sudo -S pacman -S --noconfirm kpeople
sudo -S pacman -S --noconfirm kpipewire
sudo -S pacman -S --noconfirm kpty
sudo -S pacman -S --noconfirm kquickcharts
sudo -S pacman -S --noconfirm krb5
sudo -S pacman -S --noconfirm krunner
sudo -S pacman -S --noconfirm kscreen
sudo -S pacman -S --noconfirm kscreenlocker
sudo -S pacman -S --noconfirm kservice
sudo -S pacman -S --noconfirm kstatusnotifieritem
sudo -S pacman -S --noconfirm ksvg
sudo -S pacman -S --noconfirm ksystemstats
sudo -S pacman -S --noconfirm ktexteditor
sudo -S pacman -S --noconfirm ktextwidgets
sudo -S pacman -S --noconfirm kunitconversion
sudo -S pacman -S --noconfirm kuserfeedback
sudo -S pacman -S --noconfirm kwallet
sudo -S pacman -S --noconfirm kwallet-pam
sudo -S pacman -S --noconfirm kwalletmanager
sudo -S pacman -S --noconfirm kwayland
sudo -S pacman -S --noconfirm kwidgetsaddons
sudo -S pacman -S --noconfirm kwin
sudo -S pacman -S --noconfirm kwindowsystem
sudo -S pacman -S --noconfirm kxmlgui
sudo -S pacman -S --noconfirm l-smash
sudo -S pacman -S --noconfirm lame
sudo -S pacman -S --noconfirm lapack
sudo -S pacman -S --noconfirm layer-shell-qt
sudo -S pacman -S --noconfirm layer-shell-qt5
sudo -S pacman -S --noconfirm lcms2
sudo -S pacman -S --noconfirm ldb
sudo -S pacman -S --noconfirm leancrypto
sudo -S pacman -S --noconfirm less
sudo -S pacman -S --noconfirm libaio
sudo -S pacman -S --noconfirm libarchive
sudo -S pacman -S --noconfirm libass
sudo -S pacman -S --noconfirm libassuan
sudo -S pacman -S --noconfirm libasyncns
sudo -S pacman -S --noconfirm libatasmart
sudo -S pacman -S --noconfirm libavc1394
sudo -S pacman -S --noconfirm libavtp
sudo -S pacman -S --noconfirm libb2
sudo -S pacman -S --noconfirm libblockdev
sudo -S pacman -S --noconfirm libblockdev-crypto
sudo -S pacman -S --noconfirm libblockdev-fs
sudo -S pacman -S --noconfirm libblockdev-loop
sudo -S pacman -S --noconfirm libblockdev-mdraid
sudo -S pacman -S --noconfirm libblockdev-nvme
sudo -S pacman -S --noconfirm libblockdev-part
sudo -S pacman -S --noconfirm libblockdev-swap
sudo -S pacman -S --noconfirm libbluray
sudo -S pacman -S --noconfirm libbpf
sudo -S pacman -S --noconfirm libbs2b
sudo -S pacman -S --noconfirm libbsd
sudo -S pacman -S --noconfirm libbytesize
sudo -S pacman -S --noconfirm libcaca
sudo -S pacman -S --noconfirm libcanberra
sudo -S pacman -S --noconfirm libcap
sudo -S pacman -S --noconfirm libcap-ng
sudo -S pacman -S --noconfirm libcbor
sudo -S pacman -S --noconfirm libcddb
sudo -S pacman -S --noconfirm libcdio
sudo -S pacman -S --noconfirm libcdio-paranoia
sudo -S pacman -S --noconfirm libcloudproviders
sudo -S pacman -S --noconfirm libcolord
sudo -S pacman -S --noconfirm libcups
sudo -S pacman -S --noconfirm libdaemon
sudo -S pacman -S --noconfirm libdatrie
sudo -S pacman -S --noconfirm libdc1394
sudo -S pacman -S --noconfirm libdca
sudo -S pacman -S --noconfirm libde265
sudo -S pacman -S --noconfirm libdecor
sudo -S pacman -S --noconfirm libdeflate
sudo -S pacman -S --noconfirm libdisplay-info
sudo -S pacman -S --noconfirm libdmtx
sudo -S pacman -S --noconfirm libdnet
sudo -S pacman -S --noconfirm libdovi
sudo -S pacman -S --noconfirm libdrm
sudo -S pacman -S --noconfirm libdv
sudo -S pacman -S --noconfirm libdvbpsi
sudo -S pacman -S --noconfirm libdvdcss
sudo -S pacman -S --noconfirm libdvdnav
sudo -S pacman -S --noconfirm libdvdread
sudo -S pacman -S --noconfirm libebml
sudo -S pacman -S --noconfirm libebur128
sudo -S pacman -S --noconfirm libedit
sudo -S pacman -S --noconfirm libei
sudo -S pacman -S --noconfirm libelf
sudo -S pacman -S --noconfirm libepoxy
sudo -S pacman -S --noconfirm libevdev
sudo -S pacman -S --noconfirm libevent
sudo -S pacman -S --noconfirm libfakekey
sudo -S pacman -S --noconfirm libfdk-aac
sudo -S pacman -S --noconfirm libffi
sudo -S pacman -S --noconfirm libfontenc
sudo -S pacman -S --noconfirm libfreeaptx
sudo -S pacman -S --noconfirm libftdi
sudo -S pacman -S --noconfirm libfyaml
sudo -S pacman -S --noconfirm libgcrypt
sudo -S pacman -S --noconfirm libgirepository
sudo -S pacman -S --noconfirm libgit2
sudo -S pacman -S --noconfirm libglvnd
sudo -S pacman -S --noconfirm libgme
sudo -S pacman -S --noconfirm libgoom2
sudo -S pacman -S --noconfirm libgpg-error
sudo -S pacman -S --noconfirm libgsf
sudo -S pacman -S --noconfirm libgudev
sudo -S pacman -S --noconfirm libice
sudo -S pacman -S --noconfirm libidn
sudo -S pacman -S --noconfirm libidn2
sudo -S pacman -S --noconfirm libiec61883
sudo -S pacman -S --noconfirm libimobiledevice
sudo -S pacman -S --noconfirm libimobiledevice-glue
sudo -S pacman -S --noconfirm libinih
sudo -S pacman -S --noconfirm libinput
sudo -S pacman -S --noconfirm libisl
sudo -S pacman -S --noconfirm libjcat
sudo -S pacman -S --noconfirm libjpeg-turbo
sudo -S pacman -S --noconfirm libjxl
sudo -S pacman -S --noconfirm libkate
sudo -S pacman -S --noconfirm libkdcraw
sudo -S pacman -S --noconfirm libkexiv2
sudo -S pacman -S --noconfirm libksba
sudo -S pacman -S --noconfirm libkscreen
sudo -S pacman -S --noconfirm liblc3
sudo -S pacman -S --noconfirm libldac
sudo -S pacman -S --noconfirm liblqr
sudo -S pacman -S --noconfirm liblrdf
sudo -S pacman -S --noconfirm libltc
sudo -S pacman -S --noconfirm libmad
sudo -S pacman -S --noconfirm libmatroska
sudo -S pacman -S --noconfirm libmaxminddb
sudo -S pacman -S --noconfirm libmbim
sudo -S pacman -S --noconfirm libmd
sudo -S pacman -S --noconfirm libmfx
sudo -S pacman -S --noconfirm libmicrodns
sudo -S pacman -S --noconfirm libmm-glib
sudo -S pacman -S --noconfirm libmng
sudo -S pacman -S --noconfirm libmnl
sudo -S pacman -S --noconfirm libmodplug
sudo -S pacman -S --noconfirm libmpc
sudo -S pacman -S --noconfirm libmpcdec
sudo -S pacman -S --noconfirm libmpeg2
sudo -S pacman -S --noconfirm libmspack
sudo -S pacman -S --noconfirm libmtp
sudo -S pacman -S --noconfirm libmysofa
sudo -S pacman -S --noconfirm libndp
sudo -S pacman -S --noconfirm libnetfilter_conntrack
sudo -S pacman -S --noconfirm libnewt
sudo -S pacman -S --noconfirm libnfnetlink
sudo -S pacman -S --noconfirm libnfs
sudo -S pacman -S --noconfirm libnftnl
sudo -S pacman -S --noconfirm libnghttp2
sudo -S pacman -S --noconfirm libnghttp3
sudo -S pacman -S --noconfirm libnice
sudo -S pacman -S --noconfirm libnl
sudo -S pacman -S --noconfirm libnm
sudo -S pacman -S --noconfirm libnma-common
sudo -S pacman -S --noconfirm libnma-gtk4
sudo -S pacman -S --noconfirm libnotify
sudo -S pacman -S --noconfirm libnsl
sudo -S pacman -S --noconfirm libnvme
sudo -S pacman -S --noconfirm libogg
sudo -S pacman -S --noconfirm liboggz
sudo -S pacman -S --noconfirm libopenmpt
sudo -S pacman -S --noconfirm libopenraw
sudo -S pacman -S --noconfirm libp11-kit
sudo -S pacman -S --noconfirm libpaper
sudo -S pacman -S --noconfirm libpcap
sudo -S pacman -S --noconfirm libpciaccess
sudo -S pacman -S --noconfirm libpgm
sudo -S pacman -S --noconfirm libpipeline
sudo -S pacman -S --noconfirm libpipewire
sudo -S pacman -S --noconfirm libplacebo
sudo -S pacman -S --noconfirm libplasma
sudo -S pacman -S --noconfirm libplist
sudo -S pacman -S --noconfirm libpng
sudo -S pacman -S --noconfirm libproxy
sudo -S pacman -S --noconfirm libpsl
sudo -S pacman -S --noconfirm libpulse
sudo -S pacman -S --noconfirm libqaccessibilityclient-qt6
sudo -S pacman -S --noconfirm libqalculate
sudo -S pacman -S --noconfirm libqmi
sudo -S pacman -S --noconfirm libqrtr-glib
sudo -S pacman -S --noconfirm libraqm
sudo -S pacman -S --noconfirm libraw
sudo -S pacman -S --noconfirm libraw1394
sudo -S pacman -S --noconfirm librsvg
sudo -S pacman -S --noconfirm libsamplerate
sudo -S pacman -S --noconfirm libsasl
sudo -S pacman -S --noconfirm libseccomp
sudo -S pacman -S --noconfirm libsecret
sudo -S pacman -S --noconfirm libshout
sudo -S pacman -S --noconfirm libsigc++
sudo -S pacman -S --noconfirm libsigc++-3.0
sudo -S pacman -S --noconfirm libsixel
sudo -S pacman -S --noconfirm libsm
sudo -S pacman -S --noconfirm libsndfile
sudo -S pacman -S --noconfirm libsodium
sudo -S pacman -S --noconfirm libsoup3
sudo -S pacman -S --noconfirm libsoxr
sudo -S pacman -S --noconfirm libsrtp
sudo -S pacman -S --noconfirm libssh
sudo -S pacman -S --noconfirm libssh2
sudo -S pacman -S --noconfirm libstemmer
sudo -S pacman -S --noconfirm libsysprof-capture
sudo -S pacman -S --noconfirm libtasn1
sudo -S pacman -S --noconfirm libtatsu
sudo -S pacman -S --noconfirm libteam
sudo -S pacman -S --noconfirm libthai
sudo -S pacman -S --noconfirm libtheora
sudo -S pacman -S --noconfirm libtiff
sudo -S pacman -S --noconfirm libtiger
sudo -S pacman -S --noconfirm libtirpc
sudo -S pacman -S --noconfirm libtommath
sudo -S pacman -S --noconfirm libtool
sudo -S pacman -S --noconfirm libunibreak
sudo -S pacman -S --noconfirm libunistring
sudo -S pacman -S --noconfirm libunwind
sudo -S pacman -S --noconfirm libupnp
sudo -S pacman -S --noconfirm liburcu
sudo -S pacman -S --noconfirm liburing
sudo -S pacman -S --noconfirm libusb
sudo -S pacman -S --noconfirm libusb-compat
sudo -S pacman -S --noconfirm libusbmuxd
sudo -S pacman -S --noconfirm libutempter
sudo -S pacman -S --noconfirm libuv
sudo -S pacman -S --noconfirm libva
sudo -S pacman -S --noconfirm libvdpau
sudo -S pacman -S --noconfirm libverto
sudo -S pacman -S --noconfirm libvlc
sudo -S pacman -S --noconfirm libvorbis
sudo -S pacman -S --noconfirm libvpl
sudo -S pacman -S --noconfirm libvpx
sudo -S pacman -S --noconfirm libwacom
sudo -S pacman -S --noconfirm libwbclient
sudo -S pacman -S --noconfirm libwebp
sudo -S pacman -S --noconfirm libwireplumber
sudo -S pacman -S --noconfirm libwnck3
sudo -S pacman -S --noconfirm libx11
sudo -S pacman -S --noconfirm libx86emu
sudo -S pacman -S --noconfirm libxau
sudo -S pacman -S --noconfirm libxaw
sudo -S pacman -S --noconfirm libxcb
sudo -S pacman -S --noconfirm libxcomposite
sudo -S pacman -S --noconfirm libxcrypt
sudo -S pacman -S --noconfirm libxcursor
sudo -S pacman -S --noconfirm libxcvt
sudo -S pacman -S --noconfirm libxdamage
sudo -S pacman -S --noconfirm libxdmcp
sudo -S pacman -S --noconfirm libxext
sudo -S pacman -S --noconfirm libxfixes
sudo -S pacman -S --noconfirm libxfont2
sudo -S pacman -S --noconfirm libxft
sudo -S pacman -S --noconfirm libxi
sudo -S pacman -S --noconfirm libxinerama
sudo -S pacman -S --noconfirm libxkbcommon
sudo -S pacman -S --noconfirm libxkbcommon-x11
sudo -S pacman -S --noconfirm libxkbfile
sudo -S pacman -S --noconfirm libxml2
sudo -S pacman -S --noconfirm libxmlb
sudo -S pacman -S --noconfirm libxmu
sudo -S pacman -S --noconfirm libxpm
sudo -S pacman -S --noconfirm libxpresent
sudo -S pacman -S --noconfirm libxrandr
sudo -S pacman -S --noconfirm libxrender
sudo -S pacman -S --noconfirm libxres
sudo -S pacman -S --noconfirm libxshmfence
sudo -S pacman -S --noconfirm libxslt
sudo -S pacman -S --noconfirm libxss
sudo -S pacman -S --noconfirm libxt
sudo -S pacman -S --noconfirm libxtst
sudo -S pacman -S --noconfirm libxv
sudo -S pacman -S --noconfirm libxxf86vm
sudo -S pacman -S --noconfirm libzip
sudo -S pacman -S --noconfirm licenses
sudo -S pacman -S --noconfirm lilv
sudo -S pacman -S --noconfirm linux-api-headers
sudo -S pacman -S --noconfirm linux-cachyos
sudo -S pacman -S --noconfirm linux-cachyos-headers
sudo -S pacman -S --noconfirm linux-cachyos-lts
sudo -S pacman -S --noconfirm linux-cachyos-lts-headers
sudo -S pacman -S --noconfirm linux-firmware
sudo -S pacman -S --noconfirm linux-firmware-amdgpu
sudo -S pacman -S --noconfirm linux-firmware-atheros
sudo -S pacman -S --noconfirm linux-firmware-broadcom
sudo -S pacman -S --noconfirm linux-firmware-cirrus
sudo -S pacman -S --noconfirm linux-firmware-mediatek
sudo -S pacman -S --noconfirm linux-firmware-nvidia
sudo -S pacman -S --noconfirm linux-firmware-other
sudo -S pacman -S --noconfirm linux-firmware-radeon
sudo -S pacman -S --noconfirm linux-firmware-realtek
sudo -S pacman -S --noconfirm linux-firmware-whence
sudo -S pacman -S --noconfirm lirc
sudo -S pacman -S --noconfirm live-media
sudo -S pacman -S --noconfirm lld
sudo -S pacman -S --noconfirm llhttp
sudo -S pacman -S --noconfirm llvm
sudo -S pacman -S --noconfirm llvm-libs
sudo -S pacman -S --noconfirm lm_sensors
sudo -S pacman -S --noconfirm lmdb
sudo -S pacman -S --noconfirm logrotate
sudo -S pacman -S --noconfirm lsb-release
sudo -S pacman -S --noconfirm lsscsi
sudo -S pacman -S --noconfirm lua
sudo -S pacman -S --noconfirm luajit
sudo -S pacman -S --noconfirm lv2
sudo -S pacman -S --noconfirm lvm2
sudo -S pacman -S --noconfirm lz4
sudo -S pacman -S --noconfirm lzo
sudo -S pacman -S --noconfirm m4
sudo -S pacman -S --noconfirm mailcap
sudo -S pacman -S --noconfirm make
sudo -S pacman -S --noconfirm man-db
sudo -S pacman -S --noconfirm man-pages
sudo -S pacman -S --noconfirm md4c
sudo -S pacman -S --noconfirm mdadm
sudo -S pacman -S --noconfirm media-player-info
sudo -S pacman -S --noconfirm meld
sudo -S pacman -S --noconfirm mesa
sudo -S pacman -S --noconfirm mesa-utils
sudo -S pacman -S --noconfirm micro
sudo -S pacman -S --noconfirm milou
sudo -S pacman -S --noconfirm minizip
sudo -S pacman -S --noconfirm mjpegtools
sudo -S pacman -S --noconfirm mkinitcpio
sudo -S pacman -S --noconfirm mkinitcpio-busybox
sudo -S pacman -S --noconfirm mpdecimal
sudo -S pacman -S --noconfirm mpfr
sudo -S pacman -S --noconfirm mpg123
sudo -S pacman -S --noconfirm mpv
sudo -S pacman -S --noconfirm mpvqt
sudo -S pacman -S --noconfirm mtdev
sudo -S pacman -S --noconfirm mtools
sudo -S pacman -S --noconfirm mujs
sudo -S pacman -S --noconfirm nano
sudo -S pacman -S --noconfirm nano-syntax-highlighting
sudo -S pacman -S --noconfirm ncurses
sudo -S pacman -S --noconfirm neon
sudo -S pacman -S --noconfirm netctl
sudo -S pacman -S --noconfirm nettle
sudo -S pacman -S --noconfirm networkmanager
sudo -S pacman -S --noconfirm networkmanager-openvpn
sudo -S pacman -S --noconfirm networkmanager-qt
sudo -S pacman -S --noconfirm networkmanager-vpn-plugin-openvpn
sudo -S pacman -S --noconfirm nfs-utils
sudo -S pacman -S --noconfirm nfsidmap
sudo -S pacman -S --noconfirm nftables
sudo -S pacman -S --noconfirm nilfs-utils
sudo -S pacman -S --noconfirm noto-color-emoji-fontconfig
sudo -S pacman -S --noconfirm noto-fonts
sudo -S pacman -S --noconfirm noto-fonts-cjk
sudo -S pacman -S --noconfirm noto-fonts-emoji
sudo -S pacman -S --noconfirm npth
sudo -S pacman -S --noconfirm nspr
sudo -S pacman -S --noconfirm nss
sudo -S pacman -S --noconfirm nss-mdns
sudo -S pacman -S --noconfirm ntp
sudo -S pacman -S --noconfirm numactl
sudo -S pacman -S --noconfirm ocean-sound-theme
sudo -S pacman -S --noconfirm ocl-icd
sudo -S pacman -S --noconfirm octopi
sudo -S pacman -S --noconfirm oh-my-zsh-git
sudo -S pacman -S --noconfirm onetbb
sudo -S pacman -S --noconfirm oniguruma
sudo -S pacman -S --noconfirm open-vm-tools
sudo -S pacman -S --noconfirm openal
sudo -S pacman -S --noconfirm opencore-amr
sudo -S pacman -S --noconfirm opencv
sudo -S pacman -S --noconfirm opendesktop-fonts
sudo -S pacman -S --noconfirm openexr
sudo -S pacman -S --noconfirm openh264
sudo -S pacman -S --noconfirm openjpeg2
sudo -S pacman -S --noconfirm openssh
sudo -S pacman -S --noconfirm openssl
sudo -S pacman -S --noconfirm openvpn
sudo -S pacman -S --noconfirm openxr
sudo -S pacman -S --noconfirm opus
sudo -S pacman -S --noconfirm orc
sudo -S pacman -S --noconfirm os-prober
sudo -S pacman -S --noconfirm p11-kit
sudo -S pacman -S --noconfirm pacman
sudo -S pacman -S --noconfirm pacman-contrib
sudo -S pacman -S --noconfirm pacman-mirrorlist
sudo -S pacman -S --noconfirm pacutils
sudo -S pacman -S --noconfirm pahole
sudo -S pacman -S --noconfirm pam
sudo -S pacman -S --noconfirm pambase
sudo -S pacman -S --noconfirm pango
sudo -S pacman -S --noconfirm pangomm
sudo -S pacman -S --noconfirm pangomm-2.48
sudo -S pacman -S --noconfirm parallel
sudo -S pacman -S --noconfirm parted
sudo -S pacman -S --noconfirm paru
sudo -S pacman -S --noconfirm passim
sudo -S pacman -S --noconfirm patch
sudo -S pacman -S --noconfirm pavucontrol
sudo -S pacman -S --noconfirm pciutils
sudo -S pacman -S --noconfirm pcre
sudo -S pacman -S --noconfirm pcre2
sudo -S pacman -S --noconfirm pcsclite
sudo -S pacman -S --noconfirm perl
sudo -S pacman -S --noconfirm perl-clone
sudo -S pacman -S --noconfirm perl-encode-locale
sudo -S pacman -S --noconfirm perl-error
sudo -S pacman -S --noconfirm perl-file-listing
sudo -S pacman -S --noconfirm perl-html-parser
sudo -S pacman -S --noconfirm perl-html-tagset
sudo -S pacman -S --noconfirm perl-http-cookiejar
sudo -S pacman -S --noconfirm perl-http-cookies
sudo -S pacman -S --noconfirm perl-http-daemon
sudo -S pacman -S --noconfirm perl-http-date
sudo -S pacman -S --noconfirm perl-http-message
sudo -S pacman -S --noconfirm perl-http-negotiate
sudo -S pacman -S --noconfirm perl-io-html
sudo -S pacman -S --noconfirm perl-libwww
sudo -S pacman -S --noconfirm perl-lwp-mediatypes
sudo -S pacman -S --noconfirm perl-mailtools
sudo -S pacman -S --noconfirm perl-net-http
sudo -S pacman -S --noconfirm perl-timedate
sudo -S pacman -S --noconfirm perl-try-tiny
sudo -S pacman -S --noconfirm perl-uri
sudo -S pacman -S --noconfirm perl-www-robotrules
sudo -S pacman -S --noconfirm perl-xml-parser
sudo -S pacman -S --noconfirm perl-xml-writer
sudo -S pacman -S --noconfirm phonon-qt6
sudo -S pacman -S --noconfirm phonon-qt6-vlc
sudo -S pacman -S --noconfirm pinentry
sudo -S pacman -S --noconfirm pipewire
sudo -S pacman -S --noconfirm pipewire-alsa
sudo -S pacman -S --noconfirm pipewire-audio
sudo -S pacman -S --noconfirm pipewire-pulse
sudo -S pacman -S --noconfirm pixman
sudo -S pacman -S --noconfirm pkcs11-helper
sudo -S pacman -S --noconfirm pkgconf
sudo -S pacman -S --noconfirm pkgfile
sudo -S pacman -S --noconfirm plasma-activities
sudo -S pacman -S --noconfirm plasma-activities-stats
sudo -S pacman -S --noconfirm plasma-browser-integration
sudo -S pacman -S --noconfirm plasma-desktop
sudo -S pacman -S --noconfirm plasma-firewall
sudo -S pacman -S --noconfirm plasma-integration
sudo -S pacman -S --noconfirm plasma-nm
sudo -S pacman -S --noconfirm plasma-pa
sudo -S pacman -S --noconfirm plasma-systemmonitor
sudo -S pacman -S --noconfirm plasma-thunderbolt
sudo -S pacman -S --noconfirm plasma-workspace
sudo -S pacman -S --noconfirm plasma5support
sudo -S pacman -S --noconfirm plocate
sudo -S pacman -S --noconfirm plymouth
sudo -S pacman -S --noconfirm plymouth-kcm
sudo -S pacman -S --noconfirm polkit
sudo -S pacman -S --noconfirm polkit-kde-agent
sudo -S pacman -S --noconfirm polkit-qt6
sudo -S pacman -S --noconfirm poppler
sudo -S pacman -S --noconfirm poppler-data
sudo -S pacman -S --noconfirm poppler-glib
sudo -S pacman -S --noconfirm poppler-qt6
sudo -S pacman -S --noconfirm popt
sudo -S pacman -S --noconfirm portaudio
sudo -S pacman -S --noconfirm power-profiles-daemon
sudo -S pacman -S --noconfirm powerdevil
sudo -S pacman -S --noconfirm powerline-fonts
sudo -S pacman -S --noconfirm ppp
sudo -S pacman -S --noconfirm prison
sudo -S pacman -S --noconfirm procps-ng
sudo -S pacman -S --noconfirm projectm
sudo -S pacman -S --noconfirm protobuf
sudo -S pacman -S --noconfirm protobuf-c
sudo -S pacman -S --noconfirm psmisc
sudo -S pacman -S --noconfirm pulseaudio-qt
sudo -S pacman -S --noconfirm purpose
sudo -S pacman -S --noconfirm pv
sudo -S pacman -S --noconfirm python
sudo -S pacman -S --noconfirm python-annotated-types
sudo -S pacman -S --noconfirm python-cairo
sudo -S pacman -S --noconfirm python-defusedxml
sudo -S pacman -S --noconfirm python-gobject
sudo -S pacman -S --noconfirm python-orjson
sudo -S pacman -S --noconfirm python-packaging
sudo -S pacman -S --noconfirm python-psutil
sudo -S pacman -S --noconfirm python-pydantic
sudo -S pacman -S --noconfirm python-pydantic-core
sudo -S pacman -S --noconfirm python-typing-inspection
sudo -S pacman -S --noconfirm python-typing_extensions
sudo -S pacman -S --noconfirm python-wxpython
sudo -S pacman -S --noconfirm qca-qt6
sudo -S pacman -S --noconfirm qcoro
sudo -S pacman -S --noconfirm qemu-guest-agent
sudo -S pacman -S --noconfirm qqc2-breeze-style
sudo -S pacman -S --noconfirm qqc2-desktop-style
sudo -S pacman -S --noconfirm qrencode
sudo -S pacman -S --noconfirm qt-sudo
sudo -S pacman -S --noconfirm qt5-base
sudo -S pacman -S --noconfirm qt5-declarative
sudo -S pacman -S --noconfirm qt5-translations
sudo -S pacman -S --noconfirm qt5-wayland
sudo -S pacman -S --noconfirm qt6-5compat
sudo -S pacman -S --noconfirm qt6-base
sudo -S pacman -S --noconfirm qt6-connectivity
sudo -S pacman -S --noconfirm qt6-declarative
sudo -S pacman -S --noconfirm qt6-imageformats
sudo -S pacman -S --noconfirm qt6-location
sudo -S pacman -S --noconfirm qt6-multimedia
sudo -S pacman -S --noconfirm qt6-multimedia-ffmpeg
sudo -S pacman -S --noconfirm qt6-positioning
sudo -S pacman -S --noconfirm qt6-quick3d
sudo -S pacman -S --noconfirm qt6-quicktimeline
sudo -S pacman -S --noconfirm qt6-sensors
sudo -S pacman -S --noconfirm qt6-shadertools
sudo -S pacman -S --noconfirm qt6-speech
sudo -S pacman -S --noconfirm qt6-svg
sudo -S pacman -S --noconfirm qt6-translations
sudo -S pacman -S --noconfirm qt6-virtualkeyboard
sudo -S pacman -S --noconfirm qt6-wayland
sudo -S pacman -S --noconfirm qt6-webchannel
sudo -S pacman -S --noconfirm qt6-websockets
sudo -S pacman -S --noconfirm qtermwidget
sudo -S pacman -S --noconfirm raptor
sudo -S pacman -S --noconfirm rate-mirrors
sudo -S pacman -S --noconfirm rav1e
sudo -S pacman -S --noconfirm re2
sudo -S pacman -S --noconfirm readline
sudo -S pacman -S --noconfirm rebuild-detector
sudo -S pacman -S --noconfirm reflector
sudo -S pacman -S --noconfirm ripgrep
sudo -S pacman -S --noconfirm ripgrep-all
sudo -S pacman -S --noconfirm rpcbind
sudo -S pacman -S --noconfirm rsync
sudo -S pacman -S --noconfirm rtkit
sudo -S pacman -S --noconfirm rtmpdump
sudo -S pacman -S --noconfirm rubberband
sudo -S pacman -S --noconfirm run-parts
sudo -S pacman -S --noconfirm s-nail
sudo -S pacman -S --noconfirm sbc
sudo -S pacman -S --noconfirm scx-manager
sudo -S pacman -S --noconfirm scx-scheds
sudo -S pacman -S --noconfirm sd
sudo -S pacman -S --noconfirm sddm
sudo -S pacman -S --noconfirm sddm-kcm
sudo -S pacman -S --noconfirm sdl12-compat
sudo -S pacman -S --noconfirm sdl2-compat
sudo -S pacman -S --noconfirm sdl3
sudo -S pacman -S --noconfirm sdl_image
sudo -S pacman -S --noconfirm sed
sudo -S pacman -S --noconfirm serd
sudo -S pacman -S --noconfirm sg3_utils
sudo -S pacman -S --noconfirm shaderc
sudo -S pacman -S --noconfirm shadow
sudo -S pacman -S --noconfirm shared-mime-info
sudo -S pacman -S --noconfirm signon-kwallet-extension
sudo -S pacman -S --noconfirm signon-plugin-oauth2
sudo -S pacman -S --noconfirm signon-ui
sudo -S pacman -S --noconfirm signond
sudo -S pacman -S --noconfirm slang
sudo -S pacman -S --noconfirm smartmontools
sudo -S pacman -S --noconfirm smbclient
sudo -S pacman -S --noconfirm snappy
sudo -S pacman -S --noconfirm socat
sudo -S pacman -S --noconfirm sof-firmware
sudo -S pacman -S --noconfirm solid
sudo -S pacman -S --noconfirm sonnet
sudo -S pacman -S --noconfirm sound-theme-freedesktop
sudo -S pacman -S --noconfirm soundtouch
sudo -S pacman -S --noconfirm spandsp
sudo -S pacman -S --noconfirm spdlog
sudo -S pacman -S --noconfirm spectacle
sudo -S pacman -S --noconfirm speex
sudo -S pacman -S --noconfirm speexdsp
sudo -S pacman -S --noconfirm spice-vdagent
sudo -S pacman -S --noconfirm spirv-tools
sudo -S pacman -S --noconfirm sqlite
sudo -S pacman -S --noconfirm sratom
sudo -S pacman -S --noconfirm srt
sudo -S pacman -S --noconfirm startup-notification
sudo -S pacman -S --noconfirm svt-av1
sudo -S pacman -S --noconfirm svt-hevc
sudo -S pacman -S --noconfirm syndication
sudo -S pacman -S --noconfirm syntax-highlighting
sudo -S pacman -S --noconfirm sysfsutils
sudo -S pacman -S --noconfirm systemd
sudo -S pacman -S --noconfirm systemd-libs
sudo -S pacman -S --noconfirm systemd-resolvconf
sudo -S pacman -S --noconfirm systemd-sysvcompat
sudo -S pacman -S --noconfirm systemsettings
sudo -S pacman -S --noconfirm taglib
sudo -S pacman -S --noconfirm talloc
sudo -S pacman -S --noconfirm tar
sudo -S pacman -S --noconfirm tcl
sudo -S pacman -S --noconfirm tdb
sudo -S pacman -S --noconfirm tealdeer
sudo -S pacman -S --noconfirm tevent
sudo -S pacman -S --noconfirm texinfo
sudo -S pacman -S --noconfirm thin-provisioning-tools
sudo -S pacman -S --noconfirm tinysparql
sudo -S pacman -S --noconfirm tpm2-tss
sudo -S pacman -S --noconfirm tslib
sudo -S pacman -S --noconfirm ttf-bitstream-vera
sudo -S pacman -S --noconfirm ttf-dejavu
sudo -S pacman -S --noconfirm ttf-fantasque-nerd
sudo -S pacman -S --noconfirm ttf-fira-sans
sudo -S pacman -S --noconfirm ttf-hack
sudo -S pacman -S --noconfirm ttf-liberation
sudo -S pacman -S --noconfirm ttf-meslo-nerd
sudo -S pacman -S --noconfirm ttf-opensans
sudo -S pacman -S --noconfirm twolame
sudo -S pacman -S --noconfirm tzdata
sudo -S pacman -S --noconfirm uchardet
sudo -S pacman -S --noconfirm udisks2
sudo -S pacman -S --noconfirm ufw
sudo -S pacman -S --noconfirm unrar
sudo -S pacman -S --noconfirm unzip
sudo -S pacman -S --noconfirm upower
sudo -S pacman -S --noconfirm uriparser
sudo -S pacman -S --noconfirm usb_modeswitch
sudo -S pacman -S --noconfirm usbutils
sudo -S pacman -S --noconfirm util-linux
sudo -S pacman -S --noconfirm util-linux-libs
sudo -S pacman -S --noconfirm v4l-utils
sudo -S pacman -S --noconfirm vapoursynth
sudo -S pacman -S --noconfirm verdict
sudo -S pacman -S --noconfirm vi
sudo -S pacman -S --noconfirm vid.stab
sudo -S pacman -S --noconfirm vim
sudo -S pacman -S --noconfirm vim-runtime
sudo -S pacman -S --noconfirm virtualbox-guest-utils
sudo -S pacman -S --noconfirm vlc-plugin-a52dec
sudo -S pacman -S --noconfirm vlc-plugin-aalib
sudo -S pacman -S --noconfirm vlc-plugin-alsa
sudo -S pacman -S --noconfirm vlc-plugin-aom
sudo -S pacman -S --noconfirm vlc-plugin-archive
sudo -S pacman -S --noconfirm vlc-plugin-aribb24
sudo -S pacman -S --noconfirm vlc-plugin-aribb25
sudo -S pacman -S --noconfirm vlc-plugin-avahi
sudo -S pacman -S --noconfirm vlc-plugin-bluray
sudo -S pacman -S --noconfirm vlc-plugin-caca
sudo -S pacman -S --noconfirm vlc-plugin-cddb
sudo -S pacman -S --noconfirm vlc-plugin-chromecast
sudo -S pacman -S --noconfirm vlc-plugin-dav1d
sudo -S pacman -S --noconfirm vlc-plugin-dbus
sudo -S pacman -S --noconfirm vlc-plugin-dbus-screensaver
sudo -S pacman -S --noconfirm vlc-plugin-dca
sudo -S pacman -S --noconfirm vlc-plugin-dvb
sudo -S pacman -S --noconfirm vlc-plugin-dvd
sudo -S pacman -S --noconfirm vlc-plugin-faad2
sudo -S pacman -S --noconfirm vlc-plugin-ffmpeg
sudo -S pacman -S --noconfirm vlc-plugin-firewire
sudo -S pacman -S --noconfirm vlc-plugin-flac
sudo -S pacman -S --noconfirm vlc-plugin-fluidsynth
sudo -S pacman -S --noconfirm vlc-plugin-freetype
sudo -S pacman -S --noconfirm vlc-plugin-gme
sudo -S pacman -S --noconfirm vlc-plugin-gnutls
sudo -S pacman -S --noconfirm vlc-plugin-gstreamer
sudo -S pacman -S --noconfirm vlc-plugin-inflate
sudo -S pacman -S --noconfirm vlc-plugin-jack
sudo -S pacman -S --noconfirm vlc-plugin-journal
sudo -S pacman -S --noconfirm vlc-plugin-jpeg
sudo -S pacman -S --noconfirm vlc-plugin-kate
sudo -S pacman -S --noconfirm vlc-plugin-kwallet
sudo -S pacman -S --noconfirm vlc-plugin-libsecret
sudo -S pacman -S --noconfirm vlc-plugin-lirc
sudo -S pacman -S --noconfirm vlc-plugin-live555
sudo -S pacman -S --noconfirm vlc-plugin-lua
sudo -S pacman -S --noconfirm vlc-plugin-mad
sudo -S pacman -S --noconfirm vlc-plugin-matroska
sudo -S pacman -S --noconfirm vlc-plugin-mdns
sudo -S pacman -S --noconfirm vlc-plugin-modplug
sudo -S pacman -S --noconfirm vlc-plugin-mpeg2
sudo -S pacman -S --noconfirm vlc-plugin-mpg123
sudo -S pacman -S --noconfirm vlc-plugin-mtp
sudo -S pacman -S --noconfirm vlc-plugin-musepack
sudo -S pacman -S --noconfirm vlc-plugin-nfs
sudo -S pacman -S --noconfirm vlc-plugin-notify
sudo -S pacman -S --noconfirm vlc-plugin-ogg
sudo -S pacman -S --noconfirm vlc-plugin-opus
sudo -S pacman -S --noconfirm vlc-plugin-png
sudo -S pacman -S --noconfirm vlc-plugin-pulse
sudo -S pacman -S --noconfirm vlc-plugin-quicksync
sudo -S pacman -S --noconfirm vlc-plugin-samplerate
sudo -S pacman -S --noconfirm vlc-plugin-sdl
sudo -S pacman -S --noconfirm vlc-plugin-sftp
sudo -S pacman -S --noconfirm vlc-plugin-shout
sudo -S pacman -S --noconfirm vlc-plugin-smb
sudo -S pacman -S --noconfirm vlc-plugin-soxr
sudo -S pacman -S --noconfirm vlc-plugin-speex
sudo -S pacman -S --noconfirm vlc-plugin-srt
sudo -S pacman -S --noconfirm vlc-plugin-svg
sudo -S pacman -S --noconfirm vlc-plugin-tag
sudo -S pacman -S --noconfirm vlc-plugin-theora
sudo -S pacman -S --noconfirm vlc-plugin-twolame
sudo -S pacman -S --noconfirm vlc-plugin-udev
sudo -S pacman -S --noconfirm vlc-plugin-upnp
sudo -S pacman -S --noconfirm vlc-plugin-vorbis
sudo -S pacman -S --noconfirm vlc-plugin-vpx
sudo -S pacman -S --noconfirm vlc-plugin-x264
sudo -S pacman -S --noconfirm vlc-plugin-x265
sudo -S pacman -S --noconfirm vlc-plugin-xml
sudo -S pacman -S --noconfirm vlc-plugin-zvbi
sudo -S pacman -S --noconfirm vlc-plugins-all
sudo -S pacman -S --noconfirm vlc-plugins-base
sudo -S pacman -S --noconfirm vlc-plugins-extra
sudo -S pacman -S --noconfirm vlc-plugins-video-output
sudo -S pacman -S --noconfirm vlc-plugins-visualization
sudo -S pacman -S --noconfirm vmaf
sudo -S pacman -S --noconfirm volume_key
sudo -S pacman -S --noconfirm vulkan-icd-loader
sudo -S pacman -S --noconfirm vulkan-mesa-device-select
sudo -S pacman -S --noconfirm vulkan-tools
sudo -S pacman -S --noconfirm vulkan-virtio
sudo -S pacman -S --noconfirm wayland
sudo -S pacman -S --noconfirm wayland-utils
sudo -S pacman -S --noconfirm webrtc-audio-processing-1
sudo -S pacman -S --noconfirm wget
sudo -S pacman -S --noconfirm which
sudo -S pacman -S --noconfirm wildmidi
sudo -S pacman -S --noconfirm wireless-regdb
sudo -S pacman -S --noconfirm wireplumber
sudo -S pacman -S --noconfirm wpa_supplicant
sudo -S pacman -S --noconfirm wxwidgets-common
sudo -S pacman -S --noconfirm wxwidgets-gtk3
sudo -S pacman -S --noconfirm x264
sudo -S pacman -S --noconfirm x265
sudo -S pacman -S --noconfirm xcb-proto
sudo -S pacman -S --noconfirm xcb-util
sudo -S pacman -S --noconfirm xcb-util-cursor
sudo -S pacman -S --noconfirm xcb-util-image
sudo -S pacman -S --noconfirm xcb-util-keysyms
sudo -S pacman -S --noconfirm xcb-util-renderutil
sudo -S pacman -S --noconfirm xcb-util-wm
sudo -S pacman -S --noconfirm xdg-desktop-portal
sudo -S pacman -S --noconfirm xdg-desktop-portal-gtk
sudo -S pacman -S --noconfirm xdg-desktop-portal-kde
sudo -S pacman -S --noconfirm xdg-user-dirs
sudo -S pacman -S --noconfirm xdg-utils
sudo -S pacman -S --noconfirm xf86-input-libinput
sudo -S pacman -S --noconfirm xf86-input-vmmouse
sudo -S pacman -S --noconfirm xfsprogs
sudo -S pacman -S --noconfirm xkeyboard-config
sudo -S pacman -S --noconfirm xl2tpd
sudo -S pacman -S --noconfirm xmlsec
sudo -S pacman -S --noconfirm xorg-fonts-encodings
sudo -S pacman -S --noconfirm xorg-server
sudo -S pacman -S --noconfirm xorg-server-common
sudo -S pacman -S --noconfirm xorg-setxkbmap
sudo -S pacman -S --noconfirm xorg-xauth
sudo -S pacman -S --noconfirm xorg-xdpyinfo
sudo -S pacman -S --noconfirm xorg-xinit
sudo -S pacman -S --noconfirm xorg-xinput
sudo -S pacman -S --noconfirm xorg-xkbcomp
sudo -S pacman -S --noconfirm xorg-xkill
sudo -S pacman -S --noconfirm xorg-xmodmap
sudo -S pacman -S --noconfirm xorg-xprop
sudo -S pacman -S --noconfirm xorg-xrandr
sudo -S pacman -S --noconfirm xorg-xrdb
sudo -S pacman -S --noconfirm xorg-xset
sudo -S pacman -S --noconfirm xorg-xwayland
sudo -S pacman -S --noconfirm xorgproto
sudo -S pacman -S --noconfirm xsettingsd
sudo -S pacman -S --noconfirm xvidcore
sudo -S pacman -S --noconfirm xxhash
sudo -S pacman -S --noconfirm xz
sudo -S pacman -S --noconfirm yyjson
sudo -S pacman -S --noconfirm zbar
sudo -S pacman -S --noconfirm zeromq
sudo -S pacman -S --noconfirm zimg
sudo -S pacman -S --noconfirm zix
sudo -S pacman -S --noconfirm zlib-ng
sudo -S pacman -S --noconfirm zlib-ng-compat
sudo -S pacman -S --noconfirm zram-generator
sudo -S pacman -S --noconfirm zsh
sudo -S pacman -S --noconfirm zsh-autosuggestions
sudo -S pacman -S --noconfirm zsh-completions
sudo -S pacman -S --noconfirm zsh-history-substring-search
sudo -S pacman -S --noconfirm zsh-syntax-highlighting
sudo -S pacman -S --noconfirm zsh-theme-powerlevel10k
sudo -S pacman -S --noconfirm zstd
sudo -S pacman -S --noconfirm zvbi
sudo -S pacman -S --noconfirm zxing-cpp
